### ISSUE TITLE
Remove husky

### ISSUE THREAD

**Issue by 1stdevfriend** [kentcdodds/react-hooks#1]
I've reviewed the scripts utilized by Husky as a pre-commit and pre-push hooks, and it seems they're adding unnecessary bulk to the project without significantly impacting its overall effectiveness. 

Can I proceed with removing it and submitting a pull request (PR)?

**Comment by kentcdodds** [comment]
Thanks, but I like them the way they are. Thanks anyway!

**Comment by 1stdevfriend** [comment]
Like this pre-commit hook serves hardly any purpose, yet it will still execute on every contributor's machine.


<img width="716" alt="image" src="https://github.com/kentcdodds/react-hooks/assets/27912312/39368994-4653-4d2f-a146-82f9abb6ad96">

**Comment by kentcdodds** [comment]
True, but it's useful to me. It doesn't cause harm to anyone else. I'm going to keep it. Thanks anyway!

**Comment by 1stdevfriend** [comment]
Sure.
