### ISSUE TITLE
loading state clarification

### ISSUE THREAD

**Issue by cwinters8** [kentcdodds/react-hooks#105]
For the main exercise in Lesson 6, there is this comment:
```js
// 🐨 before calling `fetchPokemon`, make sure to update the loading state
```
However, as far as I can tell at this stage we don't have a loading state, and are just returning the `<PokemonInfoFallback />` component if `pokemon` is falsy and `pokemonName` is truthy.

So I'm just wondering if I might open a PR to either clarify this comment or remove it entirely?

Thanks for the amazing course, Kent! I'm learning a bunch 😄

**Comment by kentcdodds** [comment]
Thanks! I've corrected that to recommend setting the pokemon to `null`.

@all-contributors please add @cwinters8 for bugs
