### ISSUE TITLE
Handling fetch request error without .catch

### ISSUE THREAD

**Issue by dankb82** [kentcdodds/react-hooks#107]
I have a question about the error handling extra credit in useEffect: HTTP requests. In the solution, the useEffect looks like this: 

`  React.useEffect(() => {
    if (!pokemonName) {
      return
    }
    setPokemon(null)
    setError(null)
    fetchPokemon(pokemonName).then(
      pokemon => setPokemon(pokemon),
      error => setError(error),
    )
  }, [pokemonName])`

My question is, in the event of an error, how come we don't need to implement a .catch? I don't know if I am familiar with handling the error response in the .then.

**Comment by kentcdodds** [comment]
Just updated the instructions to include a note about this. Thanks @dankb82!

8fde4a0a0f13b85b780590ce0300675d913fe4cf
