### ISSUE TITLE
Endless rerender on 02.js in Chrome when opening dev tools

### ISSUE THREAD

**Issue by OFranke** [kentcdodds/react-hooks#117]
It seems there is some interference with NextJS and this repo that is causing endless rerenders in the second course 02.js.

Luckily I have an open source NextJS repo to share on which the bug is occuring when playing together with this repo.

Reproduction:
- Copy the [gist](https://gist.github.com/OFranke/dbebd209d509bfde021f006b64f7a203) to `src/exercise/02.js`
- clone [this repo](https://github.com/OFranke/open-discourse-ui), run `yarn && yarn dev`, it should open a server on localhost:3000, wait to load the start page
- stop the server and run this repository on localhost:3000
- open the isolated page: http://localhost:3000/isolated/exercise/02.js
- refresh the page (without dev tools open) --> should be alright
- open dev tools and watch endless rerender

This is verified in Chrome 87.0.4280.141, I did not check other browsers. Here's a video of the bug: https://drive.google.com/file/d/1TQKuMjDM1CPDENWiSg8uI4l3JRPpovvz/view

**Comment by kentcdodds** [comment]
I tried to install the next app, but failed with:

```
~/Desktop/open-discourse-ui (develop) 🦍
$ npm install
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@bit%2flimebit.limebit-ui.default-headline - Not found
npm ERR! 404 
npm ERR! 404  '@bit/limebit.limebit-ui.default-headline@0.1.x' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'open-discourse-ui'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kentcdodds/.npm/_logs/2021-01-26T21_54_13_145Z-debug.log
```

I'm afraid I don't think I'll have time to dig into this. It does seem very specific to this project and is unlikely to be something wrong with this repo and more likely a problem with the next project.

Sorry!

**Comment by OFranke** [comment]
@kentcdodds 
I am sorry, the reproduction was maybe a little complicated. But I verified it's not only my project and it's not limited to the specific hooks session but to the whole site. I've reproduced it again with a fresh NextJS setup and a fresh Chrome incognito window. You can see the video here: https://drive.google.com/file/d/1oE0BHqHHlPd7Z6qNrLQNWIK9C3XH7Ian/view

Note the video might not play directly from drive but works fine when downloading.
