### ISSUE TITLE
The deployed app displays 'Uncaught RangeError`

### ISSUE THREAD

**Issue by mithi** [kentcdodds/react-hooks#118]
I don't know what that implies but I just thought it should be reported. Thanks!

<img width="1278" alt="Screen Shot 2021-01-29 at 3 57 22 PM" src="https://user-images.githubusercontent.com/1670421/106247914-2eab9c80-624b-11eb-9e99-10ad62839b87.png">

**Comment by kentcdodds** [comment]
Hi @mithi! I'm not 100% certain why this happens, but it's coming from [the MSW service worker](https://mswjs.io/) we have installed to mock backend requests (so the workshop works completely offline). I've only noticed it happens occasionally, it's unclear to me how to reproduce it, and it does not appear to impact the application, so I think we should be ok.

Thanks for reporting this. I'll keep an eye out for it.
