### ISSUE TITLE
Using template strings instead of escaping JSX

### ISSUE THREAD

**Issue by agusmoles** [kentcdodds/react-hooks#131]
Hey Kent! Thank you for the amazing course😁🚀

I was going through the React Hooks exercises and found these lines of code https://github.com/kentcdodds/react-hooks/blob/main/src/exercise/03.js#L38 and https://github.com/kentcdodds/react-hooks/blob/main/src/exercise/03.js#L33

Is there a reason to use template strings instead of espacing JSX directly to interpolate JS variables?

Thank you so much

**Comment by kentcdodds** [comment]
Hey @agusmoles,

It works the same way either way for the end-user, but React will behave slightly different. It's nothing I ever think about though. So at this point it's really just what you prefer. In general I think I prefer using template literals when I can but I can't really justify that preference 🙃 It doesn't make much difference either way though.
