### ISSUE TITLE
ErrorBoundary seems to not work with development mode

### ISSUE THREAD

**Issue by minhnguyen-paidy** [kentcdodds/react-hooks#146]
I'm working on exercise 6 with error boundary and even though my code is exactly the same as yours, it doesn't work. I still see a crashing error.

<img width="1047" alt="Screen Shot 2021-08-22 at 20 26 16" src="https://user-images.githubusercontent.com/77714029/130356919-0a95e038-a98b-40e5-98d3-8ca8e6b9d470.png">

I did a little research and seems like ErrorBoundary only works in production mode. In development mode, the red screen will still be shown for easier debugging.

If this is correct then I think it would be great if you can adjust the code template for exercise 6 or adding some notes there.

**Comment by kentcdodds** [comment]
The view that you're looking at there is not the error boundary. It's a special iframe that Create React App adds during development. If you press the little `x` at the top right of the page, you'll see what the app would look like in production.

If you want to make a pull request to add a link to this issue and explanation, then that would be welcome :)
