### ISSUE TITLE
React imports could be shorten

### ISSUE THREAD

**Issue by LingVuDev** [kentcdodds/react-hooks#168]
This is just a suggestion in almost any exercise file. Instead of write the import like this:

```js
import * as React from 'react';
``` 

it could be done like this, without the `*`:
```js
import React from 'react';
```
or even import hooks separately, like:
```js
import { useState, useEffect } from 'react';
``` 

I don't know if this feedback is helpful or not. I mean it is just a subtle difference (and maybe just personal preference as well) I just find it more common in other React projects like this.

Hope this was helpful. :)

**Comment by kentcdodds** [comment]
Hi @LingVuDev! I've actually got an article about this: https://epicreact.dev/importing-react-through-the-ages

The `import * as React from 'react'` is quite intentional :)
