### ISSUE TITLE
reset fails to udpate states other than 'squares'

### ISSUE THREAD

**Issue by newbcit** [kentcdodds/react-hooks#170]
For some reasons when reset function is invoked only the 'squares' state gets updated but others remain as is. Expected behavior would be all states get updated as a result of the 'squares' state update

**Comment by kentcdodds** [comment]
Hi!

Thanks for the question. I don't have time to answer you, but I'd be happy to answer if you'd like to bring this question to [my office hours](https://kcd.im/office-hours) then I'd be happy to answer you then. A [reproduction](https://kcd.im/repro) we can play with helps a lot as well.
