### ISSUE TITLE
[MSW] Stay integrated to browser

### ISSUE THREAD

**Issue by Mysh3ll** [kentcdodds/react-hooks#180]
Hello,

I cloned this repo and _react-fundamentals_, and from then I have the **mockServiceWorker.js** which remains attached in my browser.

How to force it to detach?

![image](https://user-images.githubusercontent.com/19687214/159503455-f9ee142a-44d3-4fb4-bf50-d96c9d535a61.png)

**Comment by kentcdodds** [comment]
Hi @Mysh3ll,

MSW should unregister itself when you close the browser, but you can unregister it manually by going to the Service Workers section of the Application tab:

<img width="821" alt="image" src="https://user-images.githubusercontent.com/1500684/159504912-b994eca7-16b2-4a5b-8568-6534c0fb54a4.png">
