### ISSUE TITLE
Code syntax highlight not working on any of the workshop repos including this one.

### ISSUE THREAD

**Issue by onso89** [kentcdodds/react-hooks#188]
I am having a hard time with the code syntax highlight on the workshop apps for any of the topics including the react-hooks, an issue that I haven't had before.

my local specs: 
- Node v16.15.0
- npm 8.5.5

I tried uninstalling and reinstalling several times no change. I have an idea what could have triggered it, I did a pull request on the repo after @kentcdodds updated the workshops to latest react 18 versions, not sure if anything happened then. Other than that no clue what could be causing an issue.

![unnamed](https://user-images.githubusercontent.com/18657434/173490713-dd4b9f44-e5e0-4fee-b21d-1e6eaac6143d.png)

**Comment by kentcdodds** [comment]
Are you seeing this on any other repos?

**Comment by onso89** [comment]
I switched to node 14 just in case and no changes, I actually have a previous repo I was working before the updated workshops the react fundamentals and it has code highlights when I run the repo. For some reason all the new repos after the update don't work. 

When I do git pull on the repo I get this, not sure if means anything since is already up to date 

<img width="579" alt="Screen Shot 2022-06-14 at 12 50 24 PM" src="https://user-images.githubusercontent.com/18657434/173632675-d34e78a4-c54d-4886-8bc0-cd0e267b9ecf.png">

**Comment by kentcdodds** [comment]
This has now been fixed in the latest version of all repos. Thanks!
