### ISSUE TITLE
React 18 state batching

### ISSUE THREAD

**Issue by WhiteMaskVarre** [kentcdodds/react-hooks#192]
i wouldn't expect it to be a huge problem it's cool thing that it might need small updated(or notification)  so people can learn about state batching and how it works since React 18 rolled the case where state batching also work on async operations
i think this is no longer an issue as i'v tried it on my actual workspace and it worked fine , or i might be the one missing something ? 

Thank your for the effort creating such beautiful and well made course ,

![AsyncBatching](https://user-images.githubusercontent.com/105864326/183308595-426169fc-965c-4c31-9770-b675d8b30466.png)

**Comment by kentcdodds** [comment]
You're correct. It's noted in the instruction:

> This is no longer the case in React 18 as it supports automatic batching for asynchronous callback too.

https://github.com/kentcdodds/react-hooks/blob/main/src/exercise/06.md#3--store-the-state-in-an-object

Thanks!
