### ISSUE TITLE
Pokmon API is not available anymore: https://graphql-pokemon.now.sh

### ISSUE THREAD

**Issue by gugol2** [kentcdodds/react-hooks#28]
Hi Ken,

Very nice material, thanks.

Just to let you know about this API that you are using for this repo is no longer working:

"ZEIT Now 1.0 is being shut down. As part of this, all ZEIT Now 1.0 Deployments will become inaccessible."

Nothing to do with your code, but just in case I let you know.
The owner of the repo has been notified already: https://github.com/lucasbento/graphql-pokemon/issues/13

Cheers!

**Comment by kentcdodds** [comment]
Ha! Dang it. Well, I know what I'm working on now 😅

I've been wanting to replace this with MSW anyway.

Thanks for letting me know.

**Comment by gugol2** [comment]
Well, apparently it works randomly...

I think replacing it with something else in the long run is a good idea.

Thanks again for this material Kent!

**Comment by marcosvega91** [comment]
Hey I can submit a PR with MSW implementation if you haven't done yet.
I have only a doubt about `react-workshop-app` because in the `setup-tests.js`  ` window.fetch` should be mocked.
Maybe an env variable like `process.env.MSW_ENABLED` can be passed from this repo to `react-workshop-app` 🤔

**Comment by kentcdodds** [comment]
I wouldn't implement this as part of `react-workshop-app`, but rather in this repo directly. If you'd like to work on this that would be welcome. We could have a similar setup here that we have in the bookshelf app.

**Comment by marcosvega91** [comment]
`MSW` will be imported in this repo but on `react-workshop-app` side we have this https://github.com/kentcdodds/react-workshop-app/blob/master/src/setup-tests.js that requires that `fetch` should be mocked

**Comment by marcosvega91** [comment]
`MSW` will be imported in this repo but on `react-workshop-app` side we have this https://github.com/kentcdodds/react-workshop-app/blob/master/src/setup-tests.js that requires that `fetch` should be mocked

**Comment by kentcdodds** [comment]
Ah, good point. Hmmmm... I set that up before I discovered MSW. I think the right approach here is to remove that from the react-workshop-app and add it to the individual apps and then later set up MSW instead.

**Comment by marcosvega91** [comment]
It should be good. I'll make a PR there

**Comment by kentcdodds** [comment]
Thanks for the help in the workshop repo @marcosvega91. I'm working on fixing this here now :)

**Comment by marcosvega91** [comment]
Goood 🚀

**Comment by gugol2** [comment]
Sorry I didn't realize you wanted collaboration for this issue @kentcdodds

**Comment by kentcdodds** [comment]
No worries @gugol2 :) Glad that you reported the issue!

**Comment by kentcdodds** [comment]
Actually... That reminds me!

@all-contributors please add @gugol2 for bugs
