### ISSUE TITLE
Incorrect reference link on exercise 2

### ISSUE THREAD

**Issue by hampallop** [kentcdodds/react-hooks#3]
On exercise 2 where it mentioned [here](https://github.com/kentcdodds/react-hooks/blob/9c611c1b0d0d2f25ac62b2908d97ff25ee98e725/src/exercise/02.md?plain=1#L113). The link is broken.
```
> PLEASE NOTE: there was a subtle change in the order of cleanup functions
> getting called in React 17:
> <https://github.com/kentcdodds/react-hooks/issues/90>
```

Looked at this repo it contains only 1 issue, so I believe you meant to refer the link to somewhere else?

**Comment by kentcdodds** [comment]
Thanks for reporting!
