### ISSUE TITLE
Is this normal? Detected Outdated Service Worker

### ISSUE THREAD

**Issue by mithi** [kentcdodds/react-hooks#43]
MacOS Catalina 10.15.16
<img width="1269" alt="Screen Shot 2020-10-03 at 7 51 41 PM" src="https://user-images.githubusercontent.com/1670421/94990902-ea1c3700-05b1-11eb-840b-57e31d1b95aa.png">

**Comment by kentcdodds** [comment]
Thanks @mithi! I've just fixed this :)
