### ISSUE TITLE
Couldn't run the react app with the npm run setup --silent on windows 

### ISSUE THREAD

**Issue by ramyatrouny** [kentcdodds/react-hooks#49]
the error output is the following 
```js
▶️  Starting workshop setup...
      Running the following command: npx "https://gist.github.com/kentcdodds/bb452ffe53a5caa3600197e1d8005733" -q
npm ERR! code 1
npm ERR! Command failed: git submodule update -q --init --recursive
npm ERR! C:/Program Files/Git/mingw64/libexec/git-core\git-submodule: line 22: .: git-sh-setup: file not found
npm ERR!
```

Even tho i tried to do an `npm install` to fix the issue it shows a different type of error and that's very weird
```js
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     **<https://npm.community>**
```

**Comment by Blazekla** [comment]
It looks like other's have run into a similar issues [here](https://github.com/kentcdodds/react-fundamentals/issues/27).

The current workaround is to do the following:

> I just ran npx git://gist.github.com/bb452ffe53a5caa3600197e1d8005733.git instead of npx https://gist.github.com/bb452ffe53a5caa3600197e1d8005733.git and that fixed it

**Comment by ethernal** [comment]
To fix this please add `[base path to git]\Git\mingw64\libexec\git-core` to your **Environment Paths**. It will allow you to run the setup. I just stumbled upon this yesterday night. There is also a Windows Defender setting that might affect this but for me it wasn't the case.

**Comment by ramyatrouny** [comment]
Thank you guys. @ethernal @Blazekla it seems it's fixed. I really appreciate your support
