### ISSUE TITLE
Link in the About section is broken

### ISSUE THREAD

**Issue by namenyi** [kentcdodds/react-hooks#6]
The https://epicreact.dev/hooks link in the About section of this repository is broken: 

<img width="318" alt="Screenshot 2024-09-19 at 08 30 39" src="https://github.com/user-attachments/assets/df780a9a-171e-4cad-b8f9-8a5ea7e10753">

---

When I click it, it redirects me to https://www.epicreact.dev/modules/react-hooks/react-hooks-welcome where I see a 404 page:

<img width="1300" alt="Screenshot 2024-09-19 at 08 30 03" src="https://github.com/user-attachments/assets/f96f7690-708e-4de6-9c78-450c1236f011">

I observe the same behaviour regardless of whether I'm logged in to epicreact.dev or not.

**Comment by kentcdodds** [comment]
Fixed. Thanks!
