### ISSUE TITLE
Issue with node setup

### ISSUE THREAD

**Issue by selinafusrc** [kentcdodds/react-hooks#7]
Here are the commands that I've ran:

C:\Users\SelinaFu>git --version
git version 2.46.2.windows.1

C:\Users\SelinaFu>node --version
v18.20.4

C:\Users\SelinaFu>npm --version
10.7.0

C:\Users\SelinaFu>git clone https://github.com/kentcdodds/react-hooks.git
Cloning into 'react-hooks'...
remote: Enumerating objects: 2635, done.
remote: Counting objects: 100% (234/234), done.
remote: Compressing objects: 100% (47/47), done.
remote: Total 2635 (delta 205), reused 187 (delta 187), pack-reused 2401 (from 1)
Receiving objects: 100% (2635/2635), 5.05 MiB | 8.77 MiB/s, done.
Resolving deltas: 100% (1746/1746), done.

C:\Users\SelinaFu>cd react-hooks

C:\Users\SelinaFu\react-hooks>node setup
▶️  Starting workshop setup...
      Running the following command: npx "https://gist.github.com/kentcdodds/bb452ffe53a5caa3600197e1d8005733" -q
npm error code ENOENT
npm error syscall lstat
npm error path C:\Users\SelinaFu\AppData\Roaming\npm
npm error errno -4058
npm error enoent ENOENT: no such file or directory, lstat 'C:\Users\SelinaFu\AppData\Roaming\npm'
npm error enoent This is related to npm not being able to find a file.
npm error enoent

npm error A complete log of this run can be found in: C:\Users\SelinaFu\AppData\Local\npm-cache\_logs\2024-10-14T13_12_58_556Z-debug-0.log

This is what is in the log:
0 verbose cli C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js
1 info using npm@10.7.0
2 info using node@v18.20.4
3 silly config:load:file:C:\Program Files\nodejs\node_modules\npm\npmrc
4 silly config:load:file:C:\Users\SelinaFu\react-hooks\.npmrc
5 silly config:load:file:C:\Users\SelinaFu\.npmrc
6 silly config:load:file:C:\Users\SelinaFu\AppData\Roaming\npm\etc\npmrc
7 verbose title npm exec https://gist.github.com/kentcdodds/bb452ffe53a5caa3600197e1d8005733 -q
8 verbose argv "exec" "--" "https://gist.github.com/kentcdodds/bb452ffe53a5caa3600197e1d8005733" "-q"
9 verbose logfile logs-max:10 dir:C:\Users\SelinaFu\AppData\Local\npm-cache\_logs\2024-10-14T13_12_58_556Z-
10 verbose logfile C:\Users\SelinaFu\AppData\Local\npm-cache\_logs\2024-10-14T13_12_58_556Z-debug-0.log
11 silly logfile start cleaning logs, removing 1 files
12 silly logfile done cleaning log files
13 verbose stack Error: ENOENT: no such file or directory, lstat 'C:\Users\SelinaFu\AppData\Roaming\npm'
14 verbose cwd C:\Users\SelinaFu\react-hooks
15 verbose Windows_NT 10.0.22631
16 verbose node v18.20.4
17 verbose npm  v10.7.0
18 error code ENOENT
19 error syscall lstat
20 error path C:\Users\SelinaFu\AppData\Roaming\npm
21 error errno -4058
22 error enoent ENOENT: no such file or directory, lstat 'C:\Users\SelinaFu\AppData\Roaming\npm'
23 error enoent This is related to npm not being able to find a file.
23 error enoent
24 verbose exit -4058
25 verbose code -4058
26 error A complete log of this run can be found in: C:\Users\SelinaFu\AppData\Local\npm-cache\_logs\2024-10-14T13_12_58_556Z-debug-0.log

**Comment by selinafusrc** [comment]
fixed with npm i -g npm

**Comment by kentcdodds** [comment]
I'm glad you found a solution.
