### ISSUE TITLE
src/__tests__/02.js fails

### ISSUE THREAD

**Issue by avrahamm** [kentcdodds/react-hooks#92]
Hello Kent!
`src/__tests__/02.js` works fine with yours final `src/final/02.extra-4.js`,
yet when just copying to `src/exercise/02.js`, same contents, 
updating test to take 
`import App from '../exercise/02' `
it fails with on line 14
`screen.getByText(/hello.*jill/i)`

Thanks!
Avraham

**Comment by kentcdodds** [comment]
Hi @avrahamm, I think you may be using an old version of the project. If you pull all the latest updates this should be fixed. Thanks!
